### PR TITLE
Made Purge Command

### PR DESCRIPTION
**Pull request by sohamjaiswal10**
finally this gonna have a purge command

### CODE REVIEW

**Comment by coodos** [comment]
change `numberOfMessages` to `count` other than that it's 🤌🏻🤌🏻🤌🏻

**Review by coodos — CHANGES_REQUESTED** [review]
`numbeOfMessages` to `count`

**Comment by sohamjaiswal10** [comment]
done 👍

**Review by coodos — APPROVED** [review]
🐬 🐬

**Pull request merged**
